name: eco_mocks_catls_cam

channels:
  - defaults
  - conda-forge

dependencies:
    - python==3.6
    - ipython
    - anaconda
    - astropy
    - h5py
    - numpy
    - pandas >= 0.22.0
    - scipy
    - seaborn
    - cython
    - sphinx >= 1.6
    - pip>=18.1
    - pip:
        - GitPython
        - progressbar2
        - cosmo-utils
        - configparser
        - sphinx-astropy
        - sphinx_rtd_theme
        - tables
        - hmf
        - requests
        - tqdm
        - CosmoloPy
